[package]
name = "rustjvm"
version = "0.1.0"
authors = ["R1tschY <r1tschy@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "^1.3.4"
clap = "^2.33.3"
cesu8 = "^1.1.0"
